feat(lang): init python (#6)
* fix(lazyvim): import `lang/python.nix` extra

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* feat(lang): init python

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* fix(python): add required plugins

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* fix(python): use venv-selector regexp branch

produces error

```
error: builder for '/nix/store/s89cjgfnyypkhx6qhh9l0fcr68xq5vz9-vimplugin-venv-selector.nvim-2024-09-15.drv' failed with exit code 1;
       last 25 log lines:
       > :Successfully required module: venv-selector.utils
       > Attempting to require module: venv-selector.user_commands
       > Entering Ex mode.  Type "visual" to go to Normal mode.
       > :Successfully required module: venv-selector.user_commands
       >
       > ======================================================
       > Require check succeeded for the following modules:
       >   - venv-selector.hooks
       >   - venv-selector.logger
       >   - venv-selector
       >   - venv-selector.venv
       >   - venv-selector.gui
       >   - venv-selector.path
       >   - venv-selector.config
       >   - venv-selector.search
       >   - venv-selector.workspace
       >   - venv-selector.utils
       >   - venv-selector.user_commands
       > All lua modules were checked.
       >
       > Require check failed for the following modules:
       >   - venv-selector.cached_venv
       >
       > Checkout https://nixos.org/manual/nixpkgs/unstable/#testing-neovim-plugins-neovim-require-check
       > ======================================================
       For full logs, run 'nix log /nix/store/s89cjgfnyypkhx6qhh9l0fcr68xq5vz9-vimplugin-venv-selector.nvim-2024-09-15.drv'.
error: 1 dependencies of derivation '/nix/store/7mw136biclnv6bj9zz8zcgkbdlk58169-neovim-0.10.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9yccjqm80zbziw6rzipxlsannfmp6897-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i6sv5d8fx5nvfwilv1233zaif0rf74xg-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c07cx1xbbrl2im92yz58sciba6zs1nv8-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kq458jqldmakyjxiyvdy5lgmlys5qcrn-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j764xmcqy2lafxcl7qf4ld2wxffc3cqh-lazyvim-test-shell-env.drv' failed to build
```

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* fix(python): use venv-selector main branch

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* fix(python): use venv-selector regexp branch

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* fix(lang): supply ruff not ruff-lsp

- https://www.github.com/LazyVim/LazyVim/pull/4126
- https://github.com/LazyVim/LazyVim/blob/541b83276e0fe92f7d0d6c9f283cd15ccba5a2fd/lua/lazyvim/plugins/extras/lang/python.lua#L5-L6

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

* nitpicks

* Remove the python TS plugin from the extra

LazyVim installs it by default.

* Remove venv-selector comment

* Format with nixfmt

* Remove debugpy from extraPackages

* Add debugpy mason package

* Change venv-selector.nvim to be optional

* Change neotest-python to be optional

* Change nvim-dap-python to be optional

* Add attrValues inherit

* Remove with expressions

* Remove whitespace

---------

Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>
Co-authored-by: Daniel Mata <100956688+matadaniel@users.noreply.github.com>